version: "3.7"
services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile-dev
    container_name: whiteboard-backend
    ports:
      - 8080:8080
    networks:
      - backend
  
networks:
  backend: